layout: default
style: whrite

user:
  email: italo.i@live.com
  bio: 'Italo José is Microsoft MVP in AI category and works at Estratégia Concursos as a machine learning engineer, he is Lead of Developer Circle SP from Facebook in São Paulo. Also is a Self-driving car assistant teacher at FIAP university in the mechatronic course and win (3º) the real self-driving car global hackathon in China by Pix Moving in 2019. He contributes with the community speaking about AI, mentoring communities by the communup.tech project and writing on medium and in the IMaster (IT Forum) as a columnist'
  # sponsorLink: your_sponsor_link
  arms: ['https://tiagomcardoso.files.wordpress.com/2019/05/mvp_logo_horizontal_preferred_cyan300_cmyk_300ppi.png?w=1100',
  'https://camo.githubusercontent.com/10b1eea06f08917338c98d9ceb9795d51a5dcea6/68747470733a2f2f7365637572652e6d65657475707374617469632e636f6d2f70686f746f732f6576656e742f612f652f632f662f686967687265735f3435323830343735312e6a706567']
  # GA: your_google_analitcs_key

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 6


social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: italojs
  # patreon: your_username
  linkedin: italojs
  mvp: 5003355
  stackoverflow: 17502
  twitter: italojs_
  telegram: italojs
  # devto: your_username
  medium: italojs
  # speakerdeck: your_username
  # youtube: your_username

topics:
  - name: OpenCV
    web_url: https://github.com/topics/opencv
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/opencv/opencv.png

  - name: Tensorflow
    web_url: https://github.com/topics/tensorflow
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/tensorflow/tensorflow.png

  - name: Scikit-learn
    web_url: https://github.com/topics/scikit-learn
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/scikit-learn/scikit-learn.png
  
  - name: TypeScript
    web_url: https://github.com/topics/typescript
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/typescript/typescript.png

  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/46beb428f6ba77f5de33ba7633402379aba5d92d/topics/python/python.png

  - name: Go
    web_url: https://github.com/topics/go
    image_url: https://raw.githubusercontent.com/github/explore/46beb428f6ba77f5de33ba7633402379aba5d92d/topics/go/go.png
  
  - name: NodeJS
    web_url: https://github.com/topics/nodejs
    image_url: https://raw.githubusercontent.com/github/explore/fd96fceccf8c42c99cbe29cf0f8dcc4736fcb85a/topics/nodejs/nodejs.png
  
  - name: Vue
    web_url: https://github.com/topics/vue
    image_url: https://raw.githubusercontent.com/github/explore/46beb428f6ba77f5de33ba7633402379aba5d92d/topics/vue/vue.png
  
  - name: Mongodb
    web_url: https://github.com/topics/mongodb
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/mongodb/mongodb.png
  
  - name: Docker
    web_url: https://github.com/topics/docker
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/docker/docker.png

  - name: Kubernetes
    web_url: https://github.com/topics/kubernetes
    image_url: https://raw.githubusercontent.com/github/explore/46beb428f6ba77f5de33ba7633402379aba5d92d/topics/kubernetes/kubernetes.png

  - name: Terraform
    web_url: https://github.com/topics/terraform
    image_url: https://raw.githubusercontent.com/github/explore/a78365e1ed698ba6441a91508591e863cf1f9590/topics/terraform/terraform.png
  
  - name: .NET
    web_url: https://github.com/topics/dotnet
    image_url: https://raw.githubusercontent.com/github/explore/93d8a67084f94b2a444e510199a6e7622e5b09a3/topics/dotnet/dotnet.png

  - name: Azure
    web_url: https://github.com/topics/azure
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/azure/azure.png
  
  - name: Awesome Lists
    web_url: https://github.com/topics/awesome
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/awesome/awesome.png
  